#!/bin/bash

#0. Setup a python virtual environment
# see Virtual_Python_install

#1. Compile the Fortran modules using f2py [included in numpy module]:

cd Modules
make all
make particles
f2py -DF2PY_REPORT_ON_ARRAY_COPY=1 -c -m romstoolsfort_old romstoolsfort_old.F




